### PR TITLE
Time routines

### PR DESCRIPTION
**Pull request by jrs65**
An update with the new time calculation routines. This should only add functionality and not break any existing code.

I've made a few small additional changes:
- Added a few helper routines for constructing useful Property objects.
  * One for specifying a float only within a certain range.
  * One for setting a UTC time that converts automatically to a UNIX time float.
- Added a changelog. We should try and keep this one up to date.
- With the new functionality I've bumped the version number up to 0.3.0.

### CODE REVIEW

**Comment by kiyo-masui** [comment]
Hrmm, the documentation isn't building on RTD (link to build log below). Maybe from upgrading sphinx? I've always found RTD super finicky.

https://readthedocs.org/projects/caput/builds/4299832

**Comment by jrs65** [comment]
And Sphinx is frequently a total shit on it's own. I'll try and setup an environment identical to the RTD one to debug.

**Comment by jrs65** [comment]
Read the docs build is fixed. The issue seems to be that I had updated the version requirements for Sphinx in `doc/requirements.txt` to one that breaks the custom read the docs build (1.4.5). Moving back to the default (1.3.5) seems to have fixed it.

**Comment by kiyo-masui** [comment]
Yup, builds: https://readthedocs.org/projects/caput/builds/4301468/

**Comment by jrs65** [comment]
Sweet. I'm going to wait for the dust to settle for a few days, to make sure there's no crazy bugs, and then I'll tag v0.3.0.

**Pull request merged**
