### PR TITLE
fix(runner): Add call to group at end of file.

### PR DESCRIPTION
**Pull request by fandinomat**
It seems runner is missing the call to group at the end of file?

### CODE REVIEW

**Comment by jrs65** [comment]
It shouldn't need it I think, the `setup.py` script will install the hooks that call `cli()`. Were you having some problem that suggests it should?

**Comment by fandinomat** [comment]
Yes, I was getting no response when scheduling a job.
I will try a fresh install and report if I still get a problem.

**Comment by fandinomat** [comment]
OK, I realize what created my problem in the first place. For the setup to call cli() the script must be ran as `caput-pipeline', not a direct call to runner.py.
The problem is, when the command `caput-pipeline queue' is issued, the script created calls runner.py directly and then nothing happens because runner.py never calls cli().

**Comment by jrs65** [comment]
Ah. Thanks Mateus, that makes much more sense. I can see why you needed that fix now. I actually think I preferred the first fix you made (i.e. adding the `if __name__ == ...` block) so can you revert to that commit and add a comment explaining why it's needed.

**Comment by fandinomat** [comment]
Done.

**Comment by fandinomat** [comment]
Done.

**Comment by fandinomat** [comment]
@jrs65 Ping.

**Pull request merged**
